### ISSUE TITLE
Папки и файлы Idea в git

### ISSUE THREAD

**Issue by kortov** [yarrtuur/LearningRepository#1]
Удали папки и файлы Idea из гитхаб, они здесь не хранятся
https://github.com/yarrtuur/LearningRepository/blob/e837643ca3284fff17e493654d5a68d3b51185c1/.idea/libraries/Maven__org_mockito_mockito_all_1_9_5.xml#L1

Добавь в корень файл .gitignore
В нем укажи 
```# Eclipse
.classpath
.project
.settings/

# Intellij
.idea/
*.iml

# Maven
log/
target/ 
```
Это исключит ненужные папки из unversioned files

**Comment by yarrtuur** [comment]
ок
