### ISSUE TITLE
Структура папок в проекте ВАЖНО

### ISSUE THREAD

**Issue by kortov** [yarrtuur/LearningRepository#2]
Порядок папок и их свойства важны. Чтобы твой проект сразу распознавался как Maven проект, расположи папки как на скрине (на bin папку не обращай внимания)
Так же сделай на папках Mark as - source/test/resource folder, папки окрасятся в нужный цвет

![screenshot 2018-05-12 16 16 27](https://user-images.githubusercontent.com/6348215/39957253-fe9e9db6-5600-11e8-8821-aa3fe9f64885.png)

**Comment by yarrtuur** [comment]
ок
